namespace: airflow

google:
  enabled: False
azure:
  enabled: False

local:
  enabled: true
  createLogPVC: true
  createDagPVC: true
  dagFolder: 
  logFolder: 

# Leave dag subpath empty as it's not an NFS subdirectory
dagVolume:
  dagSubPath: 
logVolume:
  logSubPath: 
webScheduler: 
  web:
    name: web
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
  scheduler:
    resources:
      limits:
        cpu: 300m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
  preHook:
    # This performs the migrations and runs before any new deployment or upgrade
    install: true
    initContainer: true
    args: "chown -R 50000:0 /usr/local/airflow/logs/ && airflow initdb && alembic upgrade heads"

airflowCfg:
  kubernetes:
    namespace: airflow
    workerServiceAccountName: airflow-rbac
    deleteWorkerPods: True
    # This should be the same as the webScheduler.airflowCfgConfigMap unless 
    # you are creating a second configmap. 
    # There is currently only one templated (airflow-cfg-configmap.yaml). 
    # This is named {{ .Values.webScheduler.airflowCfgConfigMap }}
    airflowConfigmap: airflow-configmap
    workerContainerRepository: quay.io/eamonkeane/airflow-k8s
    workerContainerTag: "0.5"
    # Add a list of secrets in the form of ENV_VARIABLE=KUBERNETES_SECRET_NAME=KUBERNETES_SECRET_KEY
    # This is injected into the environment of the Kubernetes Executor workers
  core:
    dagsFolder: /usr/local/airflow/dags